{
 "title": "MSR",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(sag_is_service_number_access,service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(sag_is_uptime_seconds,kubernetes_pod_name)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(sag_is_uptime_seconds,app)"
    }
   },
   {
    "name": "api",
    "query": {
     "query": "label_values(sag_microgateway_api_transaction_count,api)"
    }
   }
  ]
 },
 "panels": [
  { "title": "K8S metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MSR container memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"${application}.*\",container=\"msr\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MSR container cpu",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"${application}.*\", container=\"msr\"}[1m]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MSR cpu usage (%) $pod",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"${application}.*\", container=\"msr\"}[1m]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MSR global metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "MSR uptime $pod",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
     "repeat": "application",
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sag_is_uptime_seconds{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory usage (%) $pod",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "repeat": "application",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sag_is_used_memory_bytes{kubernetes_pod_name=~\"$pod\", app=~\"$application\"} / sag_is_max_memory_bytes{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Threads usage (%) $pod",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "repeat": "application",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sag_is_server_threads{kubernetes_pod_name=~\"$pod\", app=~\"$application\"} / sag_is_server_maxthreads{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Total service calls per minute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(sag_is_number_service_invokes{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}[1m]) * 60",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Total service errors per minute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(sag_is_number_service_errors_per_minute{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}[1m])*60",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request starts per minute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sag_is_request_starts_per_minute{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Average time per request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sag_is_avg_time_per_http_requests{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Threads usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sag_is_server_threads{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Used memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sag_is_used_memory_bytes{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Number service starts per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sag_is_service_starts_per_minute{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number service errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sag_is_number_service_errors_per_minute{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number current connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sag_is_number_current_connections{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of server threads currently active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sag_is_server_threads{kubernetes_pod_name=~\"$pod\", app=~\"$application\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "MSR service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number of calls $service per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sag_is_service_number_access{service=\"$service\"}[1m])*60",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of errors $service per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sag_is_service_number_errors{service=\"$service\"}[1m])*60",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}